name: build and test
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build_simrobo:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
        ros_distribution:
          - iron
        include:
          - docker_image: ubuntu:jammy
            ros_distribution: iron
            ros_version: 2
    container:
      image: ${{ matrix.docker_image }}
    steps:
      - name: Setup directories
        run: mkdir -p ros2_ws/src

      - name: Check out repository
        uses: actions/checkout@v4
        with:
          path: ros2_ws/src

      - name: Setup ROS environment
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: ${{ matrix.ros_distribution }}

      - name: Build and Test
        uses: ros-tooling/action-ros-ci@v0.3
        with:
          target-ros2-distro: ${{ matrix.ros_distribution }}
          package-name: |
            navista_map_launch
            navista_sensing_launch
            navista_map_msgs
            navista_map_loader
            navista_points_converter
            navista_voxel_grid_filter
